# Lab 0
#### August 28, 2025

### 1. Crash Course Review Exercises

In [5]:
# Import numpy, pandas,matplotlib, and sklearn. Also set visualizations to be shown inline in the notebook.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as skl

# Set Numpy's Random Seed to 101
np.random.seed(101)

# Create a NumPy Matrix of 100 rows by 5 columns consisting of random integers from 1-100.
# (Keep in mind that the upper limit may be exclusive.
print(np.random.randint(1, 100, size=(100, 5)))

[[96 12 82 71 64]
 [88 76 10 78 41]
 [ 5 64 41 61 93]
 [65  6 13 94 41]
 [50 84  9 30 60]
 [35 45 73 20 11]
 [77 96 88  1 74]
 [ 9 63 37 84 29]
 [64  8 11 53 57]
 [39 74 53 19 72]
 [16 45  1 13 18]
 [76 80 98 94 25]
 [37 64 20 36 31]
 [11 61 21 28  9]
 [87 27 88 47 48]
 [55 87 10 46  3]
 [19 59 93 12 11]
 [95 36 29  4 84]
 [85 48 15 70 61]
 [70 52  7 89 72]
 [69 24 36 80 99]
 [68 83 58 78 47]
 [ 4 47 30 87 22]
 [22 82 24 95 72]
 [21 28 76  6 50]
 [87 90 64 83 78]
 [ 4 57 15 50 88]
 [53 14 48 50 25]
 [21 65 53 61 48]
 [30 61 54 12 41]
 [92 46 98 25 37]
 [39 10 53 68 44]
 [ 2 80 69 69 62]
 [19 52 15 29 18]
 [88 47 53 17 71]
 [72 85 11 63 97]
 [58 24 87 86 27]
 [77 67 55 18 66]
 [58 90  3 81 51]
 [67 89 80 94  7]
 [93 43 23 21 26]
 [98 55 72 73 81]
 [94 65 64 81 39]
 [46 36 26 96 76]
 [73 12 77 80 51]
 [23 60 67  2 35]
 [38 58 36 43 45]
 [50 32 80 86  4]
 [56 74 94 95 41]
 [55 89 95 87 18]
 [69 18 19 61 84]
 [83  8 68 35 77]
 [95 21 70 74 60]
 [35 70 26 79 93]
 [75 76 34 10 44]
 [21 83 31

In [ ]:
# Create a 2-D visualization using plt.imshow of the numpy matrix with a colorbar. Add a title
# to your plot. Bonus: Figure out how to change the aspect of the imshow() plot. 